myFlask:
  component: '@serverless/tencent-flask'
  inputs:
    src:
      hook: pip3 install -r requirements.txt -t ./
      dist: ./
      exclude:
        - .env
    region: ap-guangzhou
    functionName: passive-income
    code: ./
    functionConf:
      timeout: 10
      memorySize: 128
      environment:
        variables:
          TEST: vale
      vpcConfig:
        subnetId: ''
        vpcId: ''
    apigatewayConf:
      protocols:
        - https
      environment: release